mindmap
  root((Virtuális zongora projekt))
    1. Projektelőkészítés
      1.1 Scope véglegesítés
      1.2 Projektterv kidolgozás
      1.3 Review
    2. Architektúra és audio
      2.1 Angular alapok
      2.2 Audio motor (Tone.js)
      2.3 Input optimalizálás
    3. UI és integráció
      3.1 UI tervezés
      3.2 UI implementáció
      3.3 Integráció
    4. Tesztelés
      4.1 Tesztterv
      4.2 Funkcionális teszt
      4.3 Regresszió és kompatibilitás
    5. Dokumentáció
      5.1 Megvalósítási doksi
      5.2 Záróanyagok
    6. Lezárás
      6.1 Végső ellenőrzés
      6.2 Leadás
